### PR TITLE
Fix: bugs of Blobs-DANN.ipynb for Python 3.x + Tensorflow 1.3.0

### PR DESCRIPTION
**Pull request by jindongwang**
Hi there, I've fixed the bugs for Blobs-DANN.ipynb file when using with Python 3.x + Tenforflow 1.3.0. 
I have tested it on my Mac OS  10.13.0 and Windows 10.
Can you merge that to the original file? Or you can create a branch for Python 3.x and leave the master to be 2.x. And then you can modify the readme.md file.

### CODE REVIEW

**Comment by Engineero** [comment]
You beat me to the punch, @jindongwang ! I was working on this, and then set it aside and forgot. Thanks!

**Comment by pumpikano** [comment]
Thanks so much for this. I will take a deeper look this weekend. What do you think about Tensorflow 1.4, though?

**Comment by jindongwang** [comment]
I have no idea that Tensorflow has been 1.4...
I'll look into that

**Comment by jindongwang** [comment]
@pumpikano I tested under Tensorflow 1.4.0 and the code worked perfectly well.

**Comment by pumpikano** [comment]
Thanks for the help - I updated the code for Python 3 along with some other cleanup.

**Pull request closed without merging**
